# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Storoku < Formula
  desc ""
  homepage ""
  version "0.2.38"

  on_macos do
    url "https://github.com/storacha/storoku/releases/download/v0.2.38/storoku_0.2.38_mac_os_all.zip"
    sha256 "a7d323243161cba5a4300064f8b31d4575c8974c9c40c7215e1882c99ab3dc35"

    def install
      bin.install "storoku"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/storacha/storoku/releases/download/v0.2.38/storoku_0.2.38_linux_amd64.tar.gz"
      sha256 "393649831091b72065bdd4bbb3e178ad97e7b25dece553ba79d748b0d26395b7"
      def install
        bin.install "storoku"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/storacha/storoku/releases/download/v0.2.38/storoku_0.2.38_linux_arm64.tar.gz"
      sha256 "b2d50a2899914c0bf8dbf076bd965bfe9b8caa46915a22ee2662af605bf660e1"
      def install
        bin.install "storoku"
      end
    end
  end
end
