# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Storoku < Formula
  desc ""
  homepage ""
  version "0.2.36"

  on_macos do
    url "https://github.com/storacha/storoku/releases/download/v0.2.36/storoku_0.2.36_mac_os_all.zip"
    sha256 "514da286f793a95ff02f7940c1bde19e59ca91ce804cc0ea03cf427668239e0a"

    def install
      bin.install "storoku"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/storacha/storoku/releases/download/v0.2.36/storoku_0.2.36_linux_amd64.tar.gz"
      sha256 "088b8c19532bf9a62b36bab54f77f076c246757514bb11afa0ec76b8f22e36f3"
      def install
        bin.install "storoku"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/storacha/storoku/releases/download/v0.2.36/storoku_0.2.36_linux_arm64.tar.gz"
      sha256 "d7c4f923a9da0225d644dab200fa1ac8c0ae7c8df678bea3a5dabe9badecc360"
      def install
        bin.install "storoku"
      end
    end
  end
end
